[package]
name = "quadratic-sieve"
version = "0.1.0"
authors = ["Nils Olsson <nilso@enosis.net>"]
edition = "2018"

[lib]
name = "quadratic_sieve"
path = "src/lib.rs"

[dependencies]
itertools = "0.9.0"
rand = "0.8.3"
array-init = "2.0"
#strided = "0.2.9"
